version: 0.2
env:
  parameter-store:
    S3_BUCKET: "FRONTEND_DEV_CODEPIPELINE_S3_BUCKET"
    CDN_ID: "FRONTEND_DEV_CODEPIPELINE_CDN_ID"

phases:

  pre_build:
    commands:
      echo "Entering Into PreBuild Phas"

  build:
    commands:
       - aws s3 cp build s3://${S3_BUCKET} --recursive
       - echo Build completed on `date`
       - aws cloudfront create-invalidation --distribution-id ${CDN_ID} --paths '/*'
       
artifacts:
  files:
    - '**/*'
