version: 0.2
phases:

  pre_build:
    commands:
      echo "Entering Into PreBuild Phas"

  build:
    commands:
       - aws s3 cp index.html s3://varunsandhey.feekyeyewear.com
       - echo Build completed on `date`
       - aws cloudfront create-invalidation --distribution-id E2WPUV59SGO8G8 --paths '/*'
       
artifacts:
  files:
    - '**/*'
