version: 0.2
phases:

  pre_build:
    commands:
      echo "Entering Into PreBuild Phas"

  build:
    commands:
       - aws s3 cp index.html s3://varun.feekyeyewear.com
       - echo Build completed on `date`
       - aws cloudfront create-invalidation --distribution-id E39MMO71X6Q5YP --paths '/*'
       
artifacts:
  files:
    - '**/*'
